# 这是本项目的客户端示例配置文件
# 行为：开启一个监听任何IP到代理服务器的2080端口的socks
# 与对端叫做1.1.1.1的服务器的443/https,quic端口通信
[socks5]
listen = "0.0.0.0"
port = 11763

[peer]
server = "192.168.0.2"
port = 8443
key = "e85bef458ce6a7fe1fe89fc4a2d12e7550bebede578fb54a6c829b267cd7583b"
sni = "https://www.taobao.com:443"
